# Generated by Django 3.1 on 2020-09-11 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShowBottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('image', models.ImageField(upload_to='slideshowbottom', verbose_name='显示图片')),
                ('url', models.URLField(verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '主页中部轮播图',
                'verbose_name_plural': '主页中部轮播图',
            },
        ),
        migrations.CreateModel(
            name='SlideShowTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('image', models.ImageField(upload_to='slideshowtop', verbose_name='显示图片')),
                ('url', models.URLField(verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '主页上部轮播图',
                'verbose_name_plural': '主页上部轮播图',
            },
        ),
    ]
