# Generated by Django 3.1 on 2020-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowbottom',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='slideshowtop',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='链接地址'),
        ),
    ]
