# Generated by Django 3.1 on 2020-09-11 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=20, verbose_name='机构名字')),
                ('image', models.ImageField(max_length=200, upload_to='', verbose_name='机构图片')),
                ('teacher_num', models.IntegerField(default=0, verbose_name='教师数量')),
                ('course_num', models.IntegerField(default=0, verbose_name='课程数目')),
                ('learn_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('detail_addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='详细地址')),
                ('introduce', models.TextField(verbose_name='机构介绍')),
                ('recommend_num', models.IntegerField(verbose_name='推荐指数')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.city', verbose_name='城市')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=20, verbose_name='机构类别')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=20, verbose_name='教师名字')),
                ('image', models.ImageField(upload_to='teacher/%y/%m/%d', verbose_name='头像')),
                ('work_time', models.IntegerField(default=0, verbose_name='工作年数')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('postion', models.CharField(blank=True, max_length=20, null=True, verbose_name='职位')),
                ('characteristic', models.CharField(blank=True, max_length=20, null=True, verbose_name='教学特色')),
                ('course_num', models.IntegerField(default=0, verbose_name='课程数')),
                ('learn_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('gender', models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性别')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='所在公司')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='organizationcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationcategory', verbose_name='机构类别'),
        ),
    ]
