# Generated by Django 3.1 on 2020-09-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
        migrations.AlterModelOptions(
            name='organizationcategory',
            options={'verbose_name': '机构类别', 'verbose_name_plural': '机构类别'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(max_length=200, upload_to='organization/%y/%m/%d/', verbose_name='机构图片'),
        ),
    ]
