# Generated by Django 3.1 on 2020-09-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='出生日期'),
        ),
    ]
